 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "laravel-app"
    restart: always
    working_dir: /var/www
    env_file:
      - .env 
    volumes:
      - .:/var/www/
      - ./docker/php/entrypoint.sh:/usr/local/bin/entrypoint.sh
    depends_on:
      - db 
    ports:
      - "9000:9000" 
    networks:
      - app-network

  nginx: 
    image: nginx:latest
    container_name: "laravel-app-nginx"
    volumes:
      - .:/var/www/
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5  

  db:
    image: mysql:8.0
    container_name: "laravel-app-mysql"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel  
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5



volumes:
  db_data:

    driver: local
networks:
  app-network:
    driver: bridge